name: ci

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push campuscneipe-frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/campuscneipe-frontend:latest
            ${{ secrets.REGISTRY_URL }}/campuscneipe-frontend:0.0.1
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push campuscneipe-backend
        uses: docker/build-push-action@v2
        with:
          context: ./cockpit
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/campuscneipe-backend:latest
            ${{ secrets.REGISTRY_URL }}/campuscneipe-backend:0.0.1
